DATASET:
  NAME: "BRISC"
  MODALITY: "mri"
  TRAIN_PATH: "./data/BRISC/Train_Folder/"
  VAL_PATH: "./data/BRISC/Val_Folder/"
  TEST_PATH: "./data/BRISC/Test_Folder/"
  TEXT_PROMPT_PATH: "./data/BRISC/Prompts_Folder/"
  SIZE: 224
  MASK_THRESHOLD: 127
  PREPROCESS:
    NORMALIZE: imagenet_clip
    KEEP_ASPECT_RATIO: False
    PAD_MODE: edge
    MRI_USE_COLOR_IO: True
    MRI_USE_OFFICIAL: True
    MRI_PERCENTILE_CLIP: False
    MRI_CROP_FOREGROUND: False

TEST:
  NUM_SAMPLES: 50
  USE_LATEST: True
  THRESHOLD: 0.5
  TTA:
    HFLIP: True
    VFLIP: False
    ROT90: []
    SCALES: []
  POSTPROCESS:
    ENABLE: True
    KEEP_LARGEST: True
    MIN_AREA_RATIO: 0.0001
    REMOVE_BORDER_COMPONENTS: False
    SCORE_BY_CENTER: False
    FILL_HOLES: True
    MORPH_CLOSE_K: 3
    PROB_GAUSSIAN_K: 3

MODEL:
  CLIP_MODEL: unimedclip
  BACKBONE: "ViT-B/16"
  ADAPTER_DIM: 256
  NUM_UPSCALE: 2
  BETA: 2.35
  GATE_INIT: 0.0
  LAYERS: [1,2,3,4,5,6,7,8,9,10]
  TEMPERATURE: 0.2
  DEVICE: "cuda"
  ALLOW_POSITIONAL_INTERPOLATION: True
  DECODER:
    TYPE: "w_pvl_sr"
    GLOBAL_LAYERS: [3,6,9,12]
    GLOBAL_LAYERS_ONE_BASED: True
    HYBRID_ALPHA_INIT: -1.8
    HYBRID_FUSE: True
    LOCAL_CHANNELS: [48,96,192,384]
    RETURN_AUX: True
    LOCAL_MIXSTYLE: True
    LOCAL_MIXSTYLE_P: 0.50
    LOCAL_MIXSTYLE_ALPHA: 0.30
    LOCAL_DROP_P: 0.15
